"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const facturaController_1 = require("../controllers/facturaController");
const router = (0, express_1.Router)();
router.get('/', facturaController_1.getFacturas);
router.post('/', facturaController_1.createFactura);
router.put('/:id', facturaController_1.updateFactura);
router.delete('/:id', facturaController_1.deleteFactura);
exports.default = router;
